import scheduleInterface from "./interface";

const schedule: scheduleInterface[] = [
  {
    day: "SUN",
    time: "13:00 - 15:30",
    group: "L5CG23",
    hours: "02:30",
    room: "Lab-04",
    block: "Patan HCK",
    lecturer: "Mr. Raj Pradhan",
    code: "5CS022",
    title: "Distributed and Cloud Systems Programming Workshop",
    classType: "Lab",
  },
  {
    day: "MON",
    time: "11:00 - 13:30",
    group: "L5CG23",
    hours: "02:30",
    room: "TR-09",
    block: "Chandragiri HCK",
    lecturer: "Mr. Subash Khatiwada",
    code: "5CS024",
    title: "Collaborative Development Workshop",
    classType: "Workshop",
  },
  {
    day: "TUE",
    time: "12:30 - 14:30",
    group: "L5CG23",
    hours: "02:00",
    room: "TR-07",
    block: "Bhaktapur HCK",
    lecturer: "Mr. Sachin Sherchan",
    code: "5CS020",
    title: "Human - Computer Interaction Tutorial",
    classType: "Tutorial",
  },
  {
    day: "WED",
    time: "10:30 - 13:00",
    group: "L5CG23",
    hours: "02:30",
    room: "Lab-05",
    block: "Basantapur HCK",
    lecturer: "Mr. Sachin Sherchan",
    code: "5CS020",
    title: "Human - Computer Interaction Workshop",
    classType: "Workshop",
  },
  {
    day: "WED",
    time: "14:00 - 16:00",
    group: "L5CG(21+22+23+24)",
    hours: "02:00",
    room: "LT-03",
    block: "Walsall WLV",
    lecturer: "Mr. Biraj Dulal",
    code: "5CS024",
    title: "Collaborative Development Lecture",
    classType: "Lecture",
  },
  {
    day: "THU",
    time: "09:00 - 11:00",
    group: "L5CG(21+22+23+24)",
    hours: "02:00",
    room: "LT-02",
    block: "Telford WLV",
    lecturer: "Mr. Deepson Shrestha",
    code: "5CS022",
    title: "Distributed and Cloud Systems Programming Lecture",
    classType: "Lecture",
  },
  {
    day: "THU",
    time: "13:00 - 15:00",
    group: "L5CG23",
    hours: "02:00",
    room: "TR-07",
    block: "Bhaktapur HCK",
    lecturer: "Mr. Subash Khatiwada",
    code: "5CS024",
    title: "Collaborative Development Tutorial",
    classType: "Tutorial",
  },
  {
    day: "FRI",
    time: "09:00 - 11:00",
    group: "L5CG(21+22+23+24)",
    hours: "02:00",
    room: "LT-02",
    block: "Telford WLV",
    lecturer: "Mr. Dipesh Shrestha",
    code: "5CS020",
    title: "Human - Computer Interaction Lecture",
    classType: "Lecture",
  },
  {
    day: "FRI",
    time: "13:00 - 15:00",
    group: "L5CG23",
    hours: "02:00",
    room: "TR-10",
    block: "Fulchowki HCK",
    lecturer: "Mr. Raj Pradhan",
    code: "5CS022",
    title: "Distributed and Cloud Systems Programming Tutorial",
    classType: "Tutorial",
  },
];

export { schedule };
